export const REVIEWS_DATA = [
  {
    reviewer: "Thương Lê Văn",
    avatar: "/images/avatar/avatar01.png",
    rating: 5,
    details: "1 bài đánh giá · 1 ảnh",
    time: "2 tuần trước",
    text: "Phòng Khám chuyên khoa VLTL - PHCN , điều trị các bệnh về thần kinh cột sống, đau lưng, đau cổ vai gáy,… Rất tốt.Tôi đã điều trị ở đây, rất hiệu quả và chuyên môn cao. Chúc phòng khám luôn phát triển.",
    media: [
      { src: "/images/reviews/01.png", label: null },
      { src: "/images/reviews/02.png", label: null },
    ],
  },
  {
    reviewer: "Nam Huyền Nhật",
    avatar: "/images/avatar/avatar02.png",
    rating: 5,
    details: "6 bài đánh giá · 12 ảnh",
    time: "3 tháng trước",
    text: "Tình cờ biết đến phòng khám qua một group cộng đồng. Chỉ sau một buổi thăm khám tôi quyết định cho bé theo điều trị vẹo cột sống và chân chữ X. Cảm ơn bs Tâm và bs Thịnh đã tận tâm hướng dẫn và tập cho cháu. Những lời giải thích rõ ràng và sự kiên nhẫn đã giúp cháu tiến bộ nhanh chóng.", // Đoạn text được mở rộng từ "... Thêm"
    media: [
      { src: "/images/reviews/04.png", label: "0:13" },
      { src: "/images/reviews/05.png", label: null },
    ],
  },
  {
    reviewer: "Danh Cao Tâm",
    avatar: "/images/avatar/avatar03.png",
    rating: 5,
    details: "1 bài đánh giá · 1 ảnh",
    time: "2 ngày trước",
    text: "Mình bị THCS cổ, thoát vị đa tầng có chèn tê tay. Đã đi nhiều nơi điều trị, nhưng không thấy đỡ. Sau khi điều trị ở đây được 2-3 buổi mình thấy nhẹ hơn. Tay trái bớt tê. Bác sĩ nhân viên ở đây nhiệt tình dễ thương có chuyên môn.",
    media: [
      { src: "/images/reviews/06.png", label: "0:09" },
      { src: "/images/reviews/07.png", label: null },
    ],
  },
  {
    reviewer: "Liên Man",
    avatar: "/images/avatar/avatar04.png",
    rating: 4,
    details: "6 bài đánh giá ",
    time: "3 tháng trước",
    text: "Mình đã có trải nghiệm rất tốt tại phòng khám này. Đội ngũ nhân viên rất nhiệt tình, nhẹ nhàng, luôn tận tâm tư vấn và quan tâm đến bệnh nhân. Trong suốT quá trình điều trị, mình cảm nhận được sự chuyên nghiệp và chu đáo từ các bạn. Không gian phòng khám sạch sẽ, thoáng mát, tạo cảm giác yên tâm, thoải mái khi đến thăm khám và trị liệu.",
    media: [],
  },
  {
    reviewer: "Trần Bảo Ngân",
    avatar: "/images/avatar/avatar05.png",
    rating: 5,
    details: "1 bài đánh giá ",
    time: "2 tháng trước",
    text: "Phòng khám có các bác sĩ và kỹ thuật viên nhiệt tình, phòng sạch sẽ, có hiệu quả các bệnh lý về cơ xương khớp",
    media: [],
  },
  {
    reviewer: "Thuy Duong Nguyen",
    avatar: "/images/avatar/avatar06.png",
    rating: 5,
    details: "15 bài đánh giá",
    time: "3 tháng trước",
    text: "Mình ở nước ngoài tập thể thao bị đau lưng dưới hơn nửa năm. Đợt tháng 5 rồi về tình cờ biết dc phòng khám này. Đi chụp xquang đưa bsi xem rồi làm vltl 5 hôm liền hết hẳn luôn 🤩 bsi nam nữ ai cũng dễ thương, có tâm, vui tính. Phòng có máy lạnh mát mẻ tập thoải mái lắm. Giá ca của mình là 200k/lần mà cả tiếng lận ok quá trời, có luôn xung điện hồng ngoại tê tê mà phê lắm~ Hy vọng phòng khám mở cửa lâu dài, để mỗi lần về VN mình có thể ghé làm tiếp 🥰 cổ vai gáy chẳng hạn - bệnh kinh niên của dân văn phòng bi h 🫠oạn text được mở rộng từ ",
    media: [],
  },
  {
    reviewer: "Lý Trác Quyền",
    avatar: "/images/avatar/avatar07.png",
    rating: 5,
    details: "1 bài đánh giá · 1 ảnh",
    time: "2 tháng trước",
    text: "Mình bị đau Gót chân và đau cổ vai gáy tê tay Sau 10 ngày điều trị mình đã ổn Giá cả phải chăng",
    media: [{ src: "/images/reviews/03.png", label: null }],
  },
  {
    reviewer: "Như Minh Anh Trần",
    avatar: "/images/avatar/avatar08.png",
    rating: 5,
    details: "1 bài đánh giá · 1 ảnh",
    time: "2 tháng trước",
    text: "cảm ơn cô chú đã nhiệt tình giúp con điều trị vẹo cột sống",
    media: [{ src: "/images/reviews/08.png", label: null }],
  },
];
